### PR TITLE
Fixes and minor improvements for flamegraph + stack collapse

### PR DESCRIPTION
**Pull request by ekacnet**
Add a new "perl" color, allow to annotate kernel functions and have them displayed when using color groups like "perl", "java" or others

### CODE REVIEW

**Comment by ekacnet** [comment]
Is there any problem with this pull request ?

**Comment by brendangregg** [comment]
I don't know, I haven't had a chance to look yet, sorry!

**Comment by brendangregg** [comment]
This is something I've wanted to do, and I like the simplicity in this solution. I'll include it but I'll follow up with a few tweaks:

I'll change " [k]" to "_[k]", because extra whitespace in stackcollapse output turns out to break other things.

I'll strip "_[k]" from the final flame graph.

I might switch purple to orange (which also looks good); the purple is a bit too close to the search color, and search is incredibly useful. I guess I should fix purple at some point now that search exists.

**Comment by brendangregg** [comment]
And thanks!

**Comment by ekacnet** [comment]
Thanks for merging, I could have made the adjustment in the PR

**Pull request merged**
