### PR TITLE
Unfoldall support

### PR DESCRIPTION
**Pull request by tjake**
This adds support for https://github.com/jrudolph/perf-map-agent/pull/35

You can see before/after here: https://gist.github.com/tjake/b762c51cc8a5ee89df290f2b4f361f81

Note: this patch is on top of #88

### CODE REVIEW

**Comment by brendangregg** [comment]
Thanks, I'll test it out. (And I still really need to make a test suite for stackcollapse-perf.pl, since changing the regexp's can be tricky; I did put some sample perf output in ~/test for manually checking). One hesitation I had was from an old bug with perf-map-agent unfolding, which Min Zhou reported:

> See https://github.com/jrudolph/perf-map-agent/blob/master/perf-map-agent.c#L113
> if the value of record->numpcs is zero or cur_method always equal to  top_method, the entry_p will never be assigned to an valid address, thus it will be a wild pointer. 
> This wild pointer will be passed to fprintf, which will crash the target JVM in this case.

That was many months ago, and it might have been fixed already since then. Just something I'd want to check before encouraging people to use this. :)

**Comment by tjake** [comment]
According to https://github.com/jrudolph/perf-map-agent/issues/25 it seems to be working, and based on my tests it's doing the right thing if that means anything :)

**Comment by tjake** [comment]
another commit that adds inline annotation and fixes the coloring

https://gist.github.com/tjake/6c54350c69f86f9e1be37de7866c25d8

**Comment by brendangregg** [comment]
oh good, that's how I was going to do the inline annotation too. :) That flame graph looks great.

**Comment by brendangregg** [comment]
Tested, works, thanks! Maybe you should write a blog post about this new feature and include that awesome flame graph example.

It does increase the map file size, as expected (my prod workload went from 8 Mbytes to 250), and the SVG size too. All expected...

**Comment by jrudolph** [comment]
Very nice. Thanks @tjake for pushing this change. I hacked together something similar (on which I spent only very limited time with my very limited perl skills...) but it wasn't yet ready for a PR. This looks much nicer!

**Comment by jonhoo** [comment]
Hi all! I'm working on a [Rust port](https://github.com/jonhoo/inferno/) of flamegraph, and we're about to add this feature to the port (see https://github.com/jonhoo/inferno/pull/13). Did you ever end up with a test case for this? I can't see any occurrences of `->` in the files in `test/`? If not, do any of you have some perf data laying around that might serve as a test-case? It could be included in flamegraph's test suite too (which the Rust port [actually uses](https://github.com/jonhoo/inferno/pull/11)!).

**Pull request merged**
