### PR TITLE
Add --minpercent.

### PR DESCRIPTION
**Pull request by Yamakaky**
Filtering by time percentage is more useful than filtering by pixel width, at
least in my case.

### CODE REVIEW

**Comment by Yamakaky** [comment]
The build fails, but I don't think it's related to my change.

**Comment by brendangregg** [comment]
Good idea, but the following conditions should work, which is what I think is intuitive:

- by default: elides based on minwidth of 0.1 pixels (and not 0.1%, which would be 1.2 pixels).
- --minwidth=0: elides nothing: everything is included. Ignores --minpercent (not set).
- --minpercent=0: elides nothing: everything is included. Ignores --minwidth (not set).
- --minwidth=0.5: elides less than 0.5 pixels. Ignores --minpercent (not set).
- --minpercent=0.001: elides less than 0.001 percent. Ignores --minpixels (not set).
- --minwidth=0.5 --minpercent=1: I don't have a strong opinion on what should happen if both is set. elide based on the largest? throw an error saying "pick one"? I don't mind.

I think that's how it all should work, but some of these don't work with this patch and the "||" test.

**Comment by Yamakaky** [comment]
In fact, I'm not sure `--minwidth` is necessary, in fact. SVG is vectorial, so any measure in pixels is not really relevant. I don't see a use case where `--minpercent` isn't what you want.

**Comment by Yamakaky** [comment]
What do you think of it?

**Comment by Yamakaky** [comment]
up!

**Comment by brendangregg** [comment]
I still think the tests I listed should work. So it needs logic like I wrote above to ignore the other option when one is specified.

To simplify this, I think the test itself should only be based on one type (e.g., minpixels) and if the user has specified a percentage then it is converted earlier on (minpixels = image width x percent). To avoid the ||.

**Comment by randomstuff** [comment]
What about using `--minwidth=x%` instead of adding a new flag?

**Comment by brendangregg** [comment]
Yes, that seems like a good option, by allowing a percent character, these should then happen:

by default: elides based on minwidth of 0.1 pixels (and not 0.1%, which would be 1.2 pixels).
--minwidth=0 or --minwidth=0%: elides nothing: everything is included.
--minwidth=0.5: elides less than 0.5 pixels.
--minwidth=0.5%: elides less than 0.5 percent.

**Comment by brendangregg** [comment]
Need to clean up some old PRs; as this stalled, I'm moving it to the #315 ticket. Thanks.

**Pull request closed without merging**
