### PR TITLE
Make coloring deterministic

### PR DESCRIPTION
**Pull request by SimonEismann**
This PR makes the color assigned to each function deterministic both within a flame graph and across flame graphs by using the function name hash as the random seed for the color selection.

This brings two benefits:
a) Multiple occurrences of the same function will have the same color within a flame graph
b) When using two flame graphs to do a before-after comparison of some change, both flame graphs will have identical coloring, making them easier to compare.

Here is an example of flamegraphs from two different performance tests where the coloring makes it easier to track similarities/differences:
image
image

This is a rough version, and I would clean it up and move it behind a flag, update documentation, etc., but wanted to feel out if there is any interest in this first.

### CODE REVIEW

**Comment by greenkalx** [comment]
I had the same idea please make it the default!
We do runs over a period of time to see changes in function processing times.
Currently it's hard to associate the fns between runs, hard on the eyes.
I'll pick up your change to try it, I still have the perf data to feed it.

**Comment by greenkalx** [comment]
Looks much better.
I didn't notice any performance drop from the extra processing (hashing).
My input files from stackcollapse-perf.pl are all under 3MB though.
stackcollapse-perf.pl does the heavy work with 40MB input .perf files.
I vote for making it the default. Can I approve the commit?

**Comment by SimonEismann** [comment]
@brendangregg Would this be something that could be of interest? If so, is there anything else required before merging, e.g., performance measurements on large files?

**Comment by brendangregg** [comment]
Thanks, makes sense, and I have the same question: If the CPU cost is negligible, then make it default and add a "--random" option to support the original randomness (which I sometimes play with to get a nicer-looking flame graph). If the CPU cost is noticable, then this hashing should be the option.

**Comment by SimonEismann** [comment]
@brendangregg I've added the --random flag since I haven't found any performance impact in my testing,. This is expected since we do the hashing on the folded stacks, and the changes don't impact the painting of the SVG itself.

To test this, I used a ~80MB file of folded stacks, which resulted in the following measurements using time:

Modified: 
./flamegraph.pl out.folded > kernel.svg  4.30s user 0.11s system 98% cpu 4.476 total
./flamegraph.pl out.folded > kernel.svg  4.31s user 0.09s system 98% cpu 4.485 total
./flamegraph.pl out.folded > kernel.svg  4.33s user 0.08s system 99% cpu 4.455 total
./flamegraph.pl out.folded > kernel.svg  4.20s user 0.07s system 99% cpu 4.286 total
./flamegraph.pl out.folded > kernel.svg  4.20s user 0.09s system 99% cpu 4.332 total
./flamegraph.pl out.folded > kernel.svg  4.16s user 0.09s system 99% cpu 4.282 total
./flamegraph.pl out.folded > kernel.svg  4.22s user 0.09s system 99% cpu 4.346 total
./flamegraph.pl out.folded > kernel.svg  4.24s user 0.09s system 99% cpu 4.355 total
./flamegraph.pl out.folded > kernel.svg  4.22s user 0.08s system 99% cpu 4.338 total
./flamegraph.pl out.folded > kernel.svg  4.19s user 0.09s system 99% cpu 4.318 total

Baseline
./flamegraph.pl out.folded > kernel.svg  4.20s user 0.10s system 92% cpu 4.660 total
./flamegraph.pl out.folded > kernel.svg  4.19s user 0.08s system 99% cpu 4.298 total
./flamegraph.pl out.folded > kernel.svg  4.17s user 0.07s system 99% cpu 4.278 total
./flamegraph.pl out.folded > kernel.svg  4.14s user 0.06s system 99% cpu 4.217 total
./flamegraph.pl out.folded > kernel.svg  4.17s user 0.06s system 99% cpu 4.239 total
./flamegraph.pl out.folded > kernel.svg  4.14s user 0.06s system 99% cpu 4.231 total
./flamegraph.pl out.folded > kernel.svg  4.14s user 0.06s system 99% cpu 4.219 total
./flamegraph.pl out.folded > kernel.svg  4.14s user 0.06s system 99% cpu 4.224 total
./flamegraph.pl out.folded > kernel.svg  4.14s user 0.06s system 99% cpu 4.214 total
./flamegraph.pl out.folded > kernel.svg  4.17s user 0.07s system 99% cpu 4.263 total

Below is the resulting flamegraph:
flamegraph

**Comment by matthew-olson-intel** [comment]
I agree with @SimonEismann's assessment; even a pathological use-case like [this](https://github.com/matthew-olson-intel/FlameGraph/blob/3bc979ec369455152a8880e8fc759254abefd5e8/test/bench.sh#L26) makes very little difference in performance -- the output SVG of such a Flamegraph takes longer for my browser to render than it did to generate.

For these results, `def` is the baseline, `hash` is with the already-existing `namehash` function, and `md5hash` is with this PR's proposed MD5-based hash function.

```
config: def
  avg: 5.100 ± 0.004
config: hash
  avg: 6.486 ± 0.006
config: md5hash
  avg: 5.822 ± 0.005
```

**Comment by matthew-olson-intel** [comment]
I was thinking: we don't _need_ any cryptographic sureties, collision guarantees, or really anything other than "the color is based loosely on function names." Something like MD5 does attempt to provide this, so has different design goals from what we're specifically looking for. MD5 _is_ nice because it seems to use the full gamut of yellows, oranges, and reds though.

I've played with it quite a bit more, implementing a few other "hash" functions purely meant as experiments to see how we can squeeze a little more performance out of this. As it stands, we're at around 14% overhead for the MD5 version, so that's the number to beat.

The implementations are here: https://github.com/matthew-olson-intel/FlameGraph/blob/c82c2d3766f450d45ab1a6c4ae5e3fe6909e082c/flamegraph.pl#L375

```
config: def (just calls rand)
  avg: 5.618 ± 0.087
config: hash (orig. namehash)
  avg: 7.091 ± 0.043
config: md5hash (MD5 PR)
  avg: 6.298 ± 0.029
config: simplehash (Perl loop over four characters)
  avg: 6.652 ± 0.086
config: bhash (B::hash, uses rand)
  avg: 7.641 ± 1.293
config: b2hash (B::hash, just divides by 0xFFFFFFFF)
  avg: 6.119 ± 0.041
config: sumhash (uses unpack to sum character values)
  avg: 5.900 ± 0.061
config: xshash (re-implement Perl's B::hash using XS)
  avg: 6.054 ± 0.175
```

There's a problem with `bhash`, `b2hash`, and `xshash`, though; the builtin Perl hash function is not deterministic. So unfortnately, they're immediately invalidated. Also, `xshash` requires the `Inline` Perl module, which usually isn't installed by default. Hey, they were fun to try out, though!

I'm personally partial to `sumhash`, since it solves this PR's issue of color determinism, it's got an extremely simple implementation, and its performance is good (around 5% lower than baseline).

Sources:
https://www.perlmonks.org/?node_id=11142822
https://perldoc.perl.org/perlxs

**Comment by matthew-olson-intel** [comment]
I ran quite a few more experiments. What I determined was that:
1. Calling `rand` and `srand` don't seem to affect the runtime all that much, so it doesn't matter if we call `rand(1)` one or three times. Therefore, doing fancy things like calling `rand` once and trying to split the "random" value don't give us any additional speedups.
2. The hash function largely dominates the runtime.
3. "Pure Perl" hash implementations, however clever, immediately lose to "native" implementations, so either using a module (like MD5) or rolling something custom with `unpack` and `pack` is ideal from a performance standpoint.

Based on the above results, I think it'd be quite easy to accept a ~4-5% performance hit (in a very extreme scenario like this), to make colors deterministic. Then, `--random` could enable random colors.

@SimonEismann Could you edit the PR to include this hash function instead?
```
sub sum_namehash {
  my $name = shift;
  return unpack("%32W*", $name);
}
```

**Comment by SimonEismann** [comment]
I've added your hash function, and it works like a charm! There's basically no impact on execution time anymore:
```
MD5: 4.3673 ± 0.072
New hash: 4.2749 ± 0.038
Baseline: 4.2843 ± 0.128
```
and the resulting flamegraph still looks great (The consistent coloring also helps to visualize that all the connection threads call the same functions):
new_hash_function
Thanks for helping to improve this!

**Comment by brendangregg** [comment]
Tested, works, thanks! I think the impact of this will only be realized after a year or so, when those who regularly collect flame graphs of the same target will start to realize that they are more easily comparable (unless they were using the prior --hash option, but that didn't make great use of the color range).

**Pull request merged**
